### ISSUE TITLE
other datasets

### ISSUE THREAD

**Issue by alex-j-j** [yoonkim/CNN_sentence#18]
When the code is used with a different dataset than the provided one it crashed if the longest sentence in the other dataset is longer than the longest sentence in the provided dataset. This can be fixed easily,  the max length it set in the code manually.

**Comment by HimaVarsha94** [comment]
But it is crashing when the test_model_all function is being called. How do I fix it?

**Comment by alex-j-j** [comment]
I deleted the code a long time ago. However, to deal with longer sentences you either have to increase the maximum length expected, or to pad the sentences to the already used maximum length. I will close the issue. Good luck.
