### ISSUE TITLE
how much RAM do i need to process Google News dataset bin model file?

### ISSUE THREAD

**Issue by oyvsyo** [yoonkim/CNN_sentence#45]
Maybe someone has smaller pretrained word2vec models.

**Comment by usama6832** [comment]
@oyvsyo did you get the answer? I am facing the same problem. In my case, it seems like memory is not enough to use this bin file (GoogleNews-vectors-negative300.bin)

**Comment by oyvsyo** [comment]
@usama6832 No, but I google the problem and find out, that it was possible to store these embeddings in database. 
This [lib](https://github.com/MichaMucha/emstore) was my solution, many thanks to @MichaMucha
And here is [performance measuring](https://github.com/martialblog/word_embedding_storage)

**Comment by usama6832** [comment]
@oyvsyo many thanks for your response.
